name: CI/CD - Frontend

on:
  push:
    branches: [main, develop]
    paths:
      - 'apps/mf-login/**'
      - 'apps/host/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'apps/mf-login/**'
      - 'apps/host/**'

env:
  NODE_VERSION: '18.x'
  REGISTRY: ghcr.io

jobs:
  build-mf-login:
    name: Build Microfrontend Login
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/mf-login

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint || true

      - name: Build
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mf-login-dist
          path: apps/mf-login/dist/

  build-host:
    name: Build Host Application
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/host

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint || true

      - name: Build
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: host-dist
          path: apps/host/dist/

  deploy-frontend:
    name: Deploy Frontend to Azure
    runs-on: ubuntu-latest
    needs: [build-mf-login, build-host]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: production

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Host to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: 'host-dist'
          skip_app_build: true

      - name: Azure Logout
        run: az logout
